[package]
name = "sunsetr"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
dirs = "5.0"
fs2 = "0.4.3"
signal-hook = "0.3.17"
libc = "0.2.171"
