[package]
name = "sunsetr"
version = "0.10.0"
edition = "2024"
authors = ["Cipher.J <116757358+psi4j@users.noreply.github.com>"]
description = "Automatic blue light filter for Hyprland, Niri, and everything Wayland"
license = "MIT"
repository = "https://github.com/psi4j/sunsetr"
readme = "README.md"

[features]
default = []
testing-support = []

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.145"
toml = "0.8"
dirs = "6.0"
fs2 = "0.4.3"
signal-hook = "0.3.18"
regex = "1.11"
nix = { version = "0.30.1", features = ["user", "process", "signal", "time"] }
termios = "0.3.3"
crossterm = "0.29.0"
tempfile = "3.20"
cities = "0.2.0"
chrono-tz = "0.10.3"
sunrise = "2.1.0"
tzf-rs = { version = "0.4", default-features = false }
zbus = "5.10.0"
once_cell = "1.21.3"
notify = "7.0"

# Wayland protocol support
wayland-client = { version = "0.31.11", features = ["log"] }
wayland-protocols-wlr = { version = "0.3.9", features = ["client"] }
wayland-protocols = { version = "0.32.9", features = ["client"] }
wayland-scanner = { version = "0.31.7" }
wayland-backend = { version = "0.3.11" }
sha256 = "1.6.0"

[build-dependencies]
wayland-scanner = "0.31.7"

[dev-dependencies]
sunsetr = { path = ".", features = ["testing-support"] }
tempfile = "3.20"
mockall = "0.13"
serial_test = "3.2"
env_logger = "0.11"
proptest = "1.6"
cargo-husky = "1.5.0"

[package.metadata.release]
publish = false
push = true
tag-name = "v{{version}}"
