[package]
name = "sunsetr"
version = "0.2.0"
edition = "2024"
authors = ["Cipher.J <116757358+psi4j@users.noreply.github.com>"]
description = "Automatic color temperature controller for hyprsunset"
license = "MIT"
repository = "https://github.com/psi4j/sunsetr"
readme = "README.md"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
dirs = "5.0"
fs2 = "0.4.3"
signal-hook = "0.3.17"
libc = "0.2.171"

[package.metadata.release]
publish = false
push = true
tag-name = "v{{version}}"
