# Makefile.toml - Task automation for sunsetr using cargo-make
# Install cargo-make: cargo install cargo-make
# Run tasks: cargo make <task-name>

[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.default]
description = "Show available tasks"
script = '''
echo "Sunsetr installation tasks"
echo ""
echo "Usage: cargo make <task>"
echo ""
echo "Installation tasks:"
echo "  cargo make install             - Install everything (binary, service, sleep hook)"
echo "  cargo make install-local       - Install to ~/.local (no sudo needed)"
echo "  cargo make install-binary      - Install just the binary"
echo "  cargo make install-service     - Install systemd user service"
echo "  cargo make install-sleep-hook  - Install sleep/resume hook"
echo "  cargo make uninstall           - Remove all installed files"
echo ""
echo "For development, use standard cargo commands:"
echo "  cargo build                    - Build debug binary"
echo "  cargo build --release          - Build release binary"
echo "  cargo test                     - Run tests"
echo "  cargo run -- --debug           - Run with debug output"
'''

# System Installation Tasks (requires sudo)

[tasks.install]
description = "Install sunsetr system-wide with all components"
script = '''
#!/bin/bash
set -e

echo "Building release binary..."
cargo build --release

echo "Installing sunsetr system-wide..."

# Install binary
echo "Installing binary..."
sudo install -Dm755 target/release/sunsetr /usr/bin/sunsetr

# Install systemd user service
echo "Installing systemd user service..."
sudo install -Dm644 sunsetr.service /usr/lib/systemd/user/sunsetr.service

# Install systemd sleep hook for instant resume
if [ -d "/usr/lib/systemd/system-sleep" ]; then
    echo "Installing systemd sleep hook..."
    sudo install -Dm755 system-sleep/sunsetr-resume.sh /usr/lib/systemd/system-sleep/sunsetr-resume
    echo "✓ Sleep hook installed - sunsetr will update immediately after system resume"
elif [ -d "/lib/systemd/system-sleep" ]; then
    echo "Installing systemd sleep hook..."
    sudo install -Dm755 system-sleep/sunsetr-resume.sh /lib/systemd/system-sleep/sunsetr-resume
    echo "✓ Sleep hook installed - sunsetr will update immediately after system resume"
else
    echo "⚠ Warning: systemd sleep directory not found, skipping sleep hook"
    echo "  Sunsetr will still detect resume but with a slight delay"
fi

echo ""
echo "✓ Installation complete!"
echo ""
echo "To start sunsetr as a user service:"
echo "  systemctl --user enable --now sunsetr"
echo ""
echo "Or add to your compositor config:"
echo "  Hyprland: exec-once = sunsetr"
echo "  Niri: spawn-at-startup \"sunsetr\""
'''

[tasks.install-binary]
description = "Install just the sunsetr binary"
script = '''
#!/bin/bash
echo "Building release binary..."
cargo build --release
sudo install -Dm755 target/release/sunsetr /usr/bin/sunsetr
echo "✓ Binary installed to /usr/bin/sunsetr"
'''

[tasks.install-service]
description = "Install systemd user service file"
script = '''
#!/bin/bash
sudo install -Dm644 sunsetr.service /usr/lib/systemd/user/sunsetr.service
echo "✓ Service installed. Enable with: systemctl --user enable --now sunsetr"
'''

[tasks.install-sleep-hook]
description = "Install systemd sleep hook for instant resume updates"
script = '''
#!/bin/bash
set -e

if [ ! -f "system-sleep/sunsetr-resume.sh" ]; then
    echo "Error: Sleep hook script not found at system-sleep/sunsetr-resume.sh"
    exit 1
fi

if [ -d "/usr/lib/systemd/system-sleep" ]; then
    HOOK_DEST="/usr/lib/systemd/system-sleep/sunsetr-resume"
elif [ -d "/lib/systemd/system-sleep" ]; then
    HOOK_DEST="/lib/systemd/system-sleep/sunsetr-resume"
else
    echo "Error: systemd system-sleep directory not found"
    echo "Checked: /usr/lib/systemd/system-sleep and /lib/systemd/system-sleep"
    exit 1
fi

echo "Installing sleep hook to: $HOOK_DEST"
sudo install -Dm755 system-sleep/sunsetr-resume.sh "$HOOK_DEST"
echo "✓ Sleep hook installed successfully"
echo "  Sunsetr will now update immediately when your system resumes from sleep"
'''

# Local Installation Tasks (no sudo)

[tasks.install-local]
description = "Install to ~/.local (no sudo required)"
script = '''
#!/bin/bash
set -e

echo "Building release binary..."
cargo build --release

echo "Installing sunsetr to ~/.local ..."

# Create directories if they don't exist
mkdir -p ~/.local/bin
mkdir -p ~/.local/share/systemd/user

# Install binary
install -Dm755 target/release/sunsetr ~/.local/bin/sunsetr
echo "✓ Binary installed to ~/.local/bin/sunsetr"

# Install systemd user service (modified for local path)
sed 's|/usr/bin/sunsetr|'$HOME'/.local/bin/sunsetr|' sunsetr.service > ~/.local/share/systemd/user/sunsetr.service
echo "✓ Service installed to ~/.local/share/systemd/user/sunsetr.service"

echo ""
echo "✓ Local installation complete!"
echo ""
echo "Make sure ~/.local/bin is in your PATH:"
echo '  export PATH="$HOME/.local/bin:$PATH"'
echo ""
echo "To use the systemd service:"
echo "  systemctl --user daemon-reload"
echo "  systemctl --user enable --now sunsetr"
echo ""
echo "Note: Sleep hook requires system-wide installation (cargo make install-sleep-hook)"
'''

# Uninstall Tasks

[tasks.uninstall]
description = "Remove all installed sunsetr files"
script = '''
#!/bin/bash
echo "Uninstalling sunsetr..."

# Stop service if running
systemctl --user stop sunsetr 2>/dev/null || true
systemctl --user disable sunsetr 2>/dev/null || true

# Remove system files
sudo rm -f /usr/bin/sunsetr
sudo rm -f /usr/lib/systemd/user/sunsetr.service
sudo rm -f /usr/lib/systemd/system-sleep/sunsetr-resume
sudo rm -f /lib/systemd/system-sleep/sunsetr-resume

# Remove local files
rm -f ~/.local/bin/sunsetr
rm -f ~/.local/share/systemd/user/sunsetr.service

echo "✓ Sunsetr has been uninstalled"
'''

